{{- if .Values.jobs.cacheClear.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mautic.fullname" . }}-cache-clear
  labels:
    {{- include "mautic.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded   
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ $.Chart.Name }}-cache-clear
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MAUTIC_URL
              value: "https://{{ .Values.ingress.hostname }}"
            - name: MAUTIC_DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: MAUTIC_DB_NAME 
              value: {{ .Values.database.name | quote }}
            - name: MAUTIC_DB_USER 
              value: {{ .Values.database.user | quote }}
            - name: MAUTIC_DB_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: MAUTIC_RUN_CRON_JOBS
              value: {{ .Values.runCronJobs | quote }}
            - name: MAUTIC_TRUSTED_PROXIES
              value: {{ .Values.trustedProxies | quote }}                
          args: ["/bin/sh", "-c", "php /var/www/html/bin/console cache:clear && php /var/www/html/bin/console cache:warmup && \
          chown www-data.www-data -R /var/www/html/var/cache"]      
          volumeMounts: {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        - name: mautic-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "mautic.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{ end }}
      restartPolicy: OnFailure
{{- end }}      
