apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mautic.fullname" . }}
  {{- with .Values.deploymentTemplate.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mautic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deploymentTemplate.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mautic.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MAUTIC_URL
              value: "https://{{ .Values.ingress.hostname }}"
            - name: MAUTIC_DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: MAUTIC_DB_NAME 
              value: {{ .Values.database.name | quote }}
            - name: MAUTIC_DB_USER 
              value: {{ .Values.database.user | quote }}
            - name: MAUTIC_DB_PASSWORD
              {{- if .Values.database.password }}
              value: {{ .Values.database.password | quote }}
              {{ else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "mautic.fullname" . }}
                  key: dbPassword
              {{ end }}    
            - name: MAUTIC_RUN_CRON_JOBS
              value: {{ .Values.runCronJobs | quote }}
            - name: MAUTIC_TRUSTED_PROXIES
              value: {{ .Values.trustedProxies | quote }}
          lifecycle:
            postStart:
              exec:            
                command: ["/bin/sh", "-c", "sudo -u www-data php /var/www/html/bin/console cache:warmup"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          volumeMounts:
           {{- toYaml .Values.volumeMounts | nindent 12 }}            
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}           
      volumes:
        - name: mautic-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "mautic.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{ end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
