{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mautic.fullname" . }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - secretName: {{ .Values.ingress.hostname }}
      hosts:
       - {{ .Values.ingress.hostname }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ include "mautic.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
