{{- if not .Values.database.password }}
{{- $dbPass := (randAlpha 12) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Release.Name) }}
{{- if $secret }}
{{- $dbPass = index $secret.data "dbPassword" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautic.fullname" . }}
  labels:
  {{- include "mautic.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ $dbPass}}
{{- end }}