apiVersion: v1
kind: Service
metadata:
  name: {{ include "mautic.fullname" . }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ tpl (toYaml .) $ | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mautic.selectorLabels" . | nindent 4 }}
