apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dind.fullname" . }}
  labels:
    {{- include "dind.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "dind.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dind.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dind.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: dind
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          ports:
            - name: dind
              containerPort: 2375
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 2375
          readinessProbe:
            tcpSocket:
              port: 2375
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker-data
              subPath: docker
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: docker-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "dind.fullname" .) }}
          {{- else }}
          emptyDir: { }
          {{ end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
