apiVersion: v1
kind: Service
metadata:
  name: {{ include "dind.fullname" . }}
  labels:
    {{- include "dind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dind
      protocol: TCP
      name: dind
  selector:
    {{- include "dind.selectorLabels" . | nindent 4 }}
